spring:
  redis:
    uri: redis-cli -u redis://default:MafuwkdNtfL8y8bAyu5lJwOhEiJRXdxe@redis-10540.crce286.ap-south-1-1.ec2.cloud.redislabs.com:10540
  data:
    mongodb:
      uri: mongodb+srv://ritu53649_db_user:7kGqQOqFhBDdGn3r@cluster0.o4vzqxe.mongodb.net/?appName=Cluster0
      database: journaldb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: aayush240805@gmail.com
    password: yxmr gnvr wiil zhab
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true

server:
  port: 8080
